# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13MsBST1Z32K0IVWScUWvJiQrlbPV6xAs
"""

import math

# Initialize the board
board = [' ' for _ in range(9)]

def print_board(b):
    print(f"\n {b[0]} | {b[1]} | {b[2]} ")
    print("---|---|---")
    print(f" {b[3]} | {b[4]} | {b[5]} ")
    print("---|---|---")
    print(f" {b[6]} | {b[7]} | {b[8]} \n")

def is_winner(b, letter):
    # Check rows, columns, and diagonals
    winning_conditions = [
        (0, 1, 2), (3, 4, 5), (6, 7, 8),  # Rows
        (0, 3, 6), (1, 4, 7), (2, 5, 8),  # Columns
        (0, 4, 8), (2, 4, 6)             # Diagonals
    ]
    return any(b[i] == b[j] == b[k] == letter for i, j, k in winning_conditions)

def is_board_full(b):
    return ' ' not in b

def get_empty_cells(b):
    return [i for i, spot in enumerate(b) if spot == ' ']

# Minimax algorithm for unbeatable AI
def minimax(b, is_maximizing):
    if is_winner(b, 'O'):
        return 1
    if is_winner(b, 'X'):
        return -1
    if is_board_full(b):
        return 0

    if is_maximizing:
        best_score = -math.inf
        for cell in get_empty_cells(b):
            b[cell] = 'O'
            score = minimax(b, False)
            b[cell] = ' '
            best_score = max(score, best_score)
        return best_score
    else:
        best_score = math.inf
        for cell in get_empty_cells(b):
            b[cell] = 'X'
            score = minimax(b, True)
            b[cell] = ' '
            best_score = min(score, best_score)
        return best_score

def ai_move(b):
    best_score = -math.inf
    move = None
    for cell in get_empty_cells(b):
        b[cell] = 'O'
        score = minimax(b, False)
        b[cell] = ' '
        if score > best_score:
            best_score = score
            move = cell
    b[move] = 'O'

def player_move(b):
    while True:
        try:
            choice = int(input("Choose a position (0-8): "))
            if b[choice] == ' ':
                b[choice] = 'X'
                break
            else:
                print("That spot is taken! Try again.")
        except (ValueError, IndexError):
            print("Invalid input. Enter a number between 0 and 8.")

# Main Game Loop
print("Welcome to Tic-Tac-Toe!")
print("You are 'X' and the AI is 'O'.")
print_board(board)

while True:
    player_move(board)
    print_board(board)
    if is_winner(board, 'X'):
        print("You win!")
        break
    if is_board_full(board):
        print("It's a tie!")
        break

    print("AI's turn...")
    ai_move(board)
    print_board(board)
    if is_winner(board, 'O'):
        print("AI wins!")
        break
    if is_board_full(board):
        print("It's a tie!")
        break

import random
import time

class VacuumEnvironment:
    def __init__(self):
        # Randomly initialize rooms as 'Clean' or 'Dirty'
        self.rooms = {
            'A': random.choice(['Clean', 'Dirty']),
            'B': random.choice(['Clean', 'Dirty'])
        }
        # Place the agent in a random starting room
        self.agent_location = random.choice(['A', 'B'])
        self.performance_score = 0

    def get_percept(self):
        """Returns the current location and its status."""
        status = self.rooms[self.agent_location]
        return self.agent_location, status

    def execute_action(self, action):
        """Applies the agent's action to the environment."""
        print(f"Action Executed: {action}")

        if action == 'Suck':
            self.rooms[self.agent_location] = 'Clean'
            self.performance_score += 10  # Reward for cleaning
        elif action == 'Right' and self.agent_location == 'A':
            self.agent_location = 'B'
            self.performance_score -= 1   # Small penalty for moving
        elif action == 'Left' and self.agent_location == 'B':
            self.agent_location = 'A'
            self.performance_score -= 1   # Small penalty for moving

    def display_status(self):
        print(f"Environment State: {self.rooms} | Agent Position: {self.agent_location} | Score: {self.performance_score}")
        print("-" * 65)


class ReflexVacuumAgent:
    def __init__(self):
        pass

    def choose_action(self, percept):
        """Determines action based strictly on the current percept."""
        location, status = percept

        if status == 'Dirty':
            return 'Suck'
        elif location == 'A':
            return 'Right'
        elif location == 'B':
            return 'Left'


# --- Main Simulation ---
if __name__ == "__main__":
    environment = VacuumEnvironment()
    agent = ReflexVacuumAgent()

    print("Initial State:")
    environment.display_status()

    # Run simulation for 4 time-steps
    for step in range(1, 5):
        print(f"Step {step}:")

        # 1. Agent senses the environment (Percept)
        percept = environment.get_percept()
        print(f"Agent Perceived: Location {percept[0]} is {percept[1]}")

        # 2. Agent decides on an action
        action = agent.choose_action(percept)

        # 3. Environment updates based on action
        environment.execute_action(action)
        environment.display_status()
        time.sleep(1)

"""def reflex_agent(location, status):
    '''Determine the action of the vacuum cleaner based on location and status.'''
    if status.lower() == "dirty":
        return "Suck"
    elif location.upper() == "A":
        return "Right"
    elif location.upper() == "B":
        return "Left"
    else:
        return "Unknown Location/Status"

def main():
    # Taking inputs from the user
    location = input("Enter the current location (A or B): ").strip()
    status = input("Enter the status of the location (Dirty or Clean): ").strip()
    
    # Get the action from the reflex agent function
    action = reflex_agent(location, status)
    
    # Display the result
    print(f"\n--- Vacuum Cleaner Status ---")
    print(f"Location: {location.upper()}")
    print(f"Status: {status.capitalize()}")
    print(f"Recommended Action: {action}")

if __name__ == "__main__":
    main()

"""

def reflex_agent(location, status):
    """Determine the action of the vacuum cleaner based on location and status."""
    if status.lower() == "dirty":
        return "Suck"
    elif location.upper() == "A":
        return "Right"
    elif location.upper() == "B":
        return "Left"
    else:
        return "Unknown Location/Status"

def main():
    # Taking inputs from the user
    location = input("Enter the current location (A or B): ").strip()
    status = input("Enter the status of the location (Dirty or Clean): ").strip()

    # Get the action from the reflex agent function
    action = reflex_agent(location, status)

    # Display the result
    print(f"\n--- Vacuum Cleaner Status ---")
    print(f"Location: {location.upper()}")
    print(f"Status: {status.capitalize()}")
    print(f"Recommended Action: {action}")

if __name__ == "__main__":
    main()

def reflex_vacuum_agent(location, status):
    """
    Determines the next action based on current location and its status.
    """
    if status == "Dirty":
        return "Suck"
    elif location == "A":
        return "Right"
    elif location == "B":
        return "Left"

def run_vacuum_simulation():
    print("--- Vacuum Cleaner Agent Simulation ---")

    # 1. Take inputs for the environment state
    location = input("Enter current vacuum location (A or B): ").strip().upper()
    status_A = input("Enter status of Location A (Clean or Dirty): ").strip().capitalize()
    status_B = input("Enter status of Location B (Clean or Dirty): ").strip().capitalize()

    # Store environment state in a dictionary
    environment_status = {"A": status_A, "B": status_B}

    print(f"\nInitial State: Vacuum is at {location}. Room A is {status_A}, Room B is {status_B}.\n")

    # 2. Execution loop until both locations are clean
    steps = 0
    max_steps = 4 # Safety limit to prevent infinite loops

    while (environment_status["A"] == "Dirty" or environment_status["B"] == "Dirty") and steps < max_steps:
        steps += 1
        current_status = environment_status[location]

        # Agent decides the action based on its current perception
        action = reflex_vacuum_agent(location, current_status)
        print(f"[Step {steps}] Location: {location} | Status: {current_status} -> Action Chosen: {action}")

        # 3. Apply the action to change the environment
        if action == "Suck":
            environment_status[location] = "Clean"
            print(f"-> Success: Location {location} has been cleaned.")
        elif action == "Right":
            location = "B"
            print("-> Success: Moved right to Location B.")
        elif action == "Left":
            location = "A"
            print("-> Success: Moved left to Location A.")

        print(f"Current Environment Status: Room A: {environment_status['A']}, Room B: {environment_status['B']}\n")

    # Final Goal check
    if environment_status["A"] == "Clean" and environment_status["B"] == "Clean":
        print("Goal Reached: Both locations are fully clean!")
    else:
        print("Simulation stopped.")

if __name__ == "__main__":
    run_vacuum_simulation()